### ISSUE TITLE
Third party code and binaries

### ISSUE THREAD

**Issue by SomeCrazyGuy** [thesourcerer8/hddsuperclone#11]
Currently the repo contains source, tarballs, deb packages, and binaries from several other projects both open and closed source. These projects include glade, DMDE, hdparm, and more. For DMDE in particular, I dont believe we have the rights to redistribute even unmodified binaries. I could do a pull request to remove all the files, but that will mean that livecd generation wont work - at least for now. Since we are not hosting livecd images (those are still on Scott's website) I think its acceptable to break livecd generation in the short term. If you choose to go that route I would recommend making a separate branch with the current state of the repo and rebase main to remove these large objects from the commit history.

**Comment by thesourcerer8** [comment]
I would prefer to first move to dynamically downloading those files on demand, and afterwards removing the files. I don't want to break the livecd creation, since it is actively used.

**Comment by thesourcerer8** [comment]
According to https://dmde.com/licensenew/eula_g.txt we are allowed to redistribute DMDE, so there is no urgency to remove it from my point of view.
