### ISSUE TITLE
How to compile new ubuntu iso?

### ISSUE THREAD

**Issue by DRCRecoveryData** [thesourcerer8/hddsuperclone#29]
Hi,

Xubuntu still stuck when load a bad disk in live mode so i wanna create a lastest ubuntu version with hddsuperclone,... how you compile the xubuntu to iso ?

**Comment by SomeCrazyGuy** [comment]
if you have a bad disk that is preventing the iso from booting, use the options in the bootloader to disable that sata port. practive on working drive first to see how its done before trying on failing drive.

**Comment by SomeCrazyGuy** [comment]
have you tried to set options for slow responding drives? see hddsuperclone youtube channel https://www.youtube.com/channel/UCXfHI8OX-KE_1-Tc9aCkQTQ/videos are you using direct ahci or direct usb mode?

**Comment by thesourcerer8** [comment]
I haven't tried compiling the iso yet, but there is a public/live_cd/generic-script.sh which looks like it might work. Let me know when you need any help with it.

**Comment by DRCRecoveryData** [comment]
> I haven't tried compiling the iso yet, but there is a public/live_cd/generic-script.sh which looks like it might work. Let me know when you need any help with it.

Have you made nand flash reader pcb? i wanna contribute resource or nand/emmc pinout
