### ISSUE TITLE
Guidance on using HDDSuperClone: Source Code vs. Pre-Built Binary

### ISSUE THREAD

**Issue by agyson** [thesourcerer8/hddsuperclone#32]
Hello,

I'm interested in using HDDSuperClone for cloning my damaged (corrupted) hard drive to a new one. Would you be able to provide some guidance on whether I should:

1. Build the software from source code (this repository)
2. Use the pre-built binary from the official download page

Here's the link to the HDDSuperClone download folder:
https://drive.google.com/drive/folders/1YdjHdjQbi0fig5BzCJgyGyC9tilnDJ6j (gathered from the official URL https://www.hddsuperclone.com/downloads)

I'd appreciate any insights into the advantages or considerations of each approach within the context of my use case.

Thank you!

**Comment by SomeCrazyGuy** [comment]
The official hddsuperclone lived is the easiest way to get started cloning a failing hard drive, but you will need to use hardware that is a couple years old to not have driver issues. If you build from source there are a few fixes for some crashes and a bit more performance. If this is your first time using hddsuperclone I would recommend practicing with known good drives that have no important data on them to get an idea of what the workflow is like before trying on a failing hard drive.

**Comment by agyson** [comment]
Thanks for your detailed response!
